name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: windows-latest
    strategy:
      matrix:
        arch: [x86_64, i686]
        include:
          - arch: "x86_64"
            eh: "seh"
            win32_winnt: "0x0502"
          - arch: "i686"
            eh: "dwarf"
            win32_winnt: "0x0500"

    steps:
      - uses: actions/checkout@v4

      - uses: msys2/setup-msys2@v2
        with:
          update: true

      - name: Build
        shell: msys2 {0}
        run: |
          common_args=" \
            --buildroot=/c/buildroot \
            --jobs=4 \
            --logviewer-command=cat \
            --mode=gcc-11.5.0 \
            --enable-languages=c,c++,fortran \
            --arch=${{ matrix.arch }} \
            --exceptions=${{ matrix.eh }} \
            --threads=posix \
            --rt-version=v9 \
            --with-default-win32-winnt=${{ matrix.win32_winnt }} \
            --rev=0"
          ./build $common_args --fetch-only
          ./build $common_args --bin-compress

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.arch }}
          path: C:/buildroot/archives/*.7z

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            C:/buildroot/archives/*.7z
